config/routes.rb
class AdminConstraint
  def self.matches?(request)
    if request.session[:user_id]
      user = User.find request.session[:user_id]
      user && user.admin?
    end
  end
end

Rails.application.routes.draw do
  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  post 'markdown/preview', to: 'markdown#preview'

  resources :users, only: [:create] do
    collection do
      get :check_email
      get :check_username
    end
  end

  namespace :users do
    resource :password, only: [:show, :new, :create, :edit, :update]
    resource :confirmation, only: [:new, :show, :create]
  end

  concern :commentable do
    resources :comments, only: [:create]
  end

  concern :likeable do
    resource :like, only: [:create, :destroy]
  end

  concern :subscribable do
    resource :subscription, only: [:update, :destroy]
  end

  resources :topics, only: [:index, :show, :new, :create, :edit, :update], concerns: [:commentable, :likeable, :subscribable] do
    collection do
      get 'categoried/:category_id', to: 'topics#index', as: :categoried
      get 'search'
    end

    member do
      delete :trash
    end
  end

  resources :comments, only: [:edit, :update], concerns: [:likeable] do
    member do
      get :cancel
      delete :trash
    end
  end

  resources :notifications, only: [:index, :destroy] do
    collection do
      post :mark
      delete :clear
    end
  end

  resources :attachments, only: [:create]

  root 'topics#index'

  scope path: '~:username', module: 'users', as: 'user' do
    resources :topics, only: [:index] do
      collection do
        get :likes
      end
    end
    resources :comments, only: [:index] do
      collection do
        get :likes
      end
    end

    root to: 'topics#index'
  end

  namespace :settings do
    resource :account, only: [:show, :update]
    resource :password, only: [:show, :update]
    resource :profile, only: [:show, :update]
    resource :notifications, only: [:show, :update]
  end

  namespace :admin do
    root to: 'dashboard#show'

    resources :users, only: [:index, :show, :update, :destroy] do
      collection do
        get :locked
      end

      member do
        patch :lock
        delete :lock, action: 'unlock'
      end
    end

    resources :categories, except: [:edit]

    resources :topics, only: [:index, :show, :update] do
      collection do
        get :trashed
      end

      member do
        delete :trash
        patch :restore
      end
    end

    resources :comments, only: [:index, :show, :update] do
      collection do
        get :trashed
      end

      member do
        delete :trash
        patch :restore
      end
    end

    resources :attachments, only: [:index, :destroy]
  end

  constraints(AdminConstraint) do
    mount Resque::Server.new, at: 'resque'
  end

  if Rails.env.development?
    get 'qunit', to: 'qunit#index'
  end
end

app/models/topic.rb
class Topic < ActiveRecord::Base
  include Likeable
  include Trashable
  include Subscribable
  include Elasticsearch::Model
  include Elasticsearch::Model::Callbacks

  belongs_to :user
  belongs_to :category, counter_cache: true
  has_many :comments, as: 'commentable'

  validates :title, :body, presence: true

  after_create :update_hot, :owner_subscribe
  after_touch :update_hot

  def calculate_hot
    order = Math.log10([comments_count, 1].max)
    order + created_at.to_f / 45000
  end

  def update_hot
    # reload because comments_count has been cache in associations
    reload
    update_attribute :hot, calculate_hot
  end

  def owner_subscribe
    subscribe_by user
  end

  def total_pages
    (comments_count.to_f / Comment.default_per_page).ceil
  end

  def more_like_this(num = 5)
    Topic.search(
      query: {
        more_like_this: {
          fields: ['title', 'body'],
          like_text: title + '\n' + body
        }
      },
      filter: {
        and: [
          { term: { trashed: false } },
          { not: { term: { id: id } } }
        ]
      }
    ).limit(num).records.to_a rescue []
  end
end

app/controllers/admin/topics_controller.rb
class Admin::TopicsController < Admin::ApplicationController
  before_action :find_topic, only: [:show, :update, :trash, :restore]

  def index
    @topics = Topic.includes(:user).order(id: :desc).page(params[:page])
  end

  def trashed
    @topics = Topic.trashed.includes(:user).order(id: :desc).page(params[:page])
    render :index
  end

  def show
  end

  def update
    if @topic.update_attributes params.require(:topic).permit(:title, :category_id, :body)
      flash[:success] = I18n.t('admin.topics.flashes.successfully_updated')
      redirect_to admin_topic_url(@topic)
    else
      render :show
    end
  end

  def trash
    @topic.trash
    flash[:success] = I18n.t('admin.topics.flashes.successfully_trashed')
    redirect_to admin_topic_path(@topic)
  end

  def restore
    @topic.restore
    flash[:success] = I18n.t('admin.topics.flashes.successfully_restored')
    redirect_to admin_topic_path(@topic)
  end

  private

  def find_topic
    @topic = Topic.with_trashed.find params[:id]
  end
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  before_action :login_required, :no_locked_required, except: [:index, :show, :search]
  before_action :find_topic, only: [:edit, :update, :trash]

  def index
    @topics = Topic.includes(:user, :category).page(params[:page])

    if params[:category_id]
      @category = Category.where('lower(slug) = ?', params[:category_id].downcase).first!
      @topics = @topics.where(category: @category)
    end

    # Set default tab
    unless %w(hot newest).include? params[:tab]
      params[:tab] = 'hot'
    end

    case params[:tab]
    when 'hot'
      @topics = @topics.order(hot: :desc)
    when 'newest'
      @topics = @topics.order(id: :desc)
    end
  end

  def search
    @topics = Topic.search(
      query: {
        multi_match: {
          query: params[:q].to_s,
          fields: ['title', 'body']
        }
      },
      filter: {
        term: {
          trashed: false
        }
      }
    ).page(params[:page]).records
  end

  def show
    @topic = Topic.find params[:id]

    if params[:comment_id] and comment = @topic.comments.find_by(id: params.delete(:comment_id))
      params[:page] = comment.page
    end

    @comments = @topic.comments.includes(:user).order(id: :asc).page(params[:page])

    respond_to do |format|
      format.html
    end
  end

  def new
    @category = Category.where('lower(slug) = ?', params[:category_id].downcase).first if params[:category_id].present?
    @topic = Topic.new category: @category
  end

  def create
    @topic = current_user.topics.create topic_params
  end

  def edit
  end

  def update
    @topic.update_attributes topic_params
  end

  def trash
    @topic.trash
    redirect_via_turbolinks_to topics_path
  end

  private

  def topic_params
    params.require(:topic).permit(:title, :category_id, :body)
  end

  def find_topic
    @topic = current_user.topics.find params[:id]
  end
end

app/controllers/users/topics_controller.rb
class Users::TopicsController < Users::ApplicationController
  def index
    @topics = @user.topics.includes(:category).order(id: :desc).page(params[:page])
  end

  def likes
    @topics = @user.like_topics.includes(:category, :user).order(id: :desc).page(params[:page])
    render :index
  end
end

app/helpers/admin/topics_helper.rb
module Admin::TopicsHelper
  def link_to_admin_topic(topic)
    if topic.nil?
      "Topic had been destroy"
    else
      link_to topic.title, admin_topic_path(topic)
    end
  end
end

app/helpers/topics_helper.rb
module TopicsHelper
  def topic_last_path(topic)
    topic_path(topic, page: (topic.total_pages if topic.total_pages > 1), anchor: (topic.comments_count if topic.comments_count > 0))
  end
end

app/views/topics/_form.html.slim
= form_for @topic, remote: true, html: { class: 'topic-form' } do |f|
  .row
    .col-md-9
      .form-group
        = f.text_field :title, class: 'form-control', placeholder: t('.title'), tabIndex: 1
    .col-md-3
      .form-group
        = f.collection_select :category_id, Category.order(topics_count: :desc), :id, :name, { include_blank: t('.no_category')}, class: 'form-control', tabIndex: 2
  .form-group
    = markdown_area f, :body, tabIndex: 3
  - if topic.new_record?
    = f.submit t('.create_topic'), class: 'btn btn-success', tabIndex: 4, 'data-disable-with' => t('.create_topic')
  - else
    = f.submit t('.save_changes'), class: 'btn btn-success', tabIndex: 4, 'data-disable-with' => t('.save_changes')
    '
    a.btn.btn-default href=topic_path(@topic) tabIndex="5"
      = t '.cancel'

- form_id = @topic.new_record? ? 'new_topic' : "edit_topic_#{@topic.id}"

javascript:
  $('##{form_id}').validate({
    rules: {
      'topic[title]': {
        required: true
      },
      'topic[body]': {
        required: true
      }
    },
    messages: {
      'topic[title]': {
        required: '#{@topic.errors.generate_message :title, :blank}'
      },
      'topic[body]': {
        required: '#{@topic.errors.generate_message :body, :blank}'
      }
    }
  });

app/views/topics/_search_form.html.slim
.panel
  .panel-body
    = form_tag search_topics_path, method: 'get', class: 'search-form', data: { behaviors: 'turboform' } do
      .input-group
        = text_field_tag :q, params[:q], class: 'form-control', tabIndex: 1, autocomplete: 'off', autofocus: params[:q].present?
        .input-group-btn
          button.btn.btn-default type='submit' tabIndex="2"
            i.fa.fa-search

app/views/topics/_topic.html.slim
- cache [topic, locale] do
  a.list-group-item.topic href=topic_last_path(topic)
    .list-group-item-avatar
      img.img-rounded alt="avatar" src=topic.user.avatar.normal.url
    .list-group-item-content
      .list-group-item-heading
        b = topic.title
      .text-muted
        = topic.user.name
        = ' · '
        = time_ago_tag topic.created_at
        - if topic.category
          = ' · '
          = topic.category.name
        = ' · '
        = t '.comments_count', count: topic.comments_count

app/views/topics/create.js.erb
<% if @topic.errors.empty? %>
  Turbolinks.visit('<%= topic_path(@topic) %>');
<% end %>

app/views/topics/edit.html.slim
- @page_title = t '.edit_topic'

.main
  .container
    .row
      .col-md-9
        .panel
          .panel-heading
            h3.panel-title = t '.edit_topic'
          .panel-body
            = render 'form', topic: @topic

app/views/topics/index.html.slim
- case params[:tab]
- when 'hot'
  - @page_title = t('.hot_topics')
- when 'newest'
  - @page_title = t('.newest_topics')

- if @category
  - @page_title += " #{@category.name}"

.main
  .container
    .row
      .col-md-9
        .panel
          .panel-heading.clearfix
            .pull-right
              ul.nav.nav-pills
                li class=('active' if params[:tab] == 'hot')
                  a href=url_for(tab: 'hot')
                    = t '.hot'
                li class=('active' if params[:tab] == 'newest')
                  a href=url_for(tab: 'newest')
                    = t '.newest'
            h3.panel-title
              = @category.try(:name) || t('.all_categories')

          - if @category && @category.description.present?
            .panel-body
              = markdown_format @category.description

          .panel-body
            .list-group.list-group-campo.recordable
              - if @topics.any?
                = render @topics
              - else
                .list-group-item.text-center.text-muted.empty-message
                  = t '.no_topic_yet'
          - if @topics.total_pages > 1
            .panel-footer.clearfix
              .pull-right
                = paginate @topics, theme: 'campo'

      .col-md-3
        = render 'search_form'
        .panel
          .panel-body
            a.btn.btn-success.btn-block href=new_topic_path(category_id: @category.try(:slug))
              = t '.create_topic'
        .panel
          .panel-body
            ul.nav.nav-pills.nav-stacked
              li class=('active' unless @category)
                a href=topics_path
                  = t '.all_categories'
              - Category.order(topics_count: :desc).each do |category|
                li class=('active' if category == @category)
                  a href=categoried_topics_path(category_id: category.slug)
                    = category.name

app/views/topics/new.html.slim
- @page_title = t '.new_topic'

.main
  .container
    .row
      .col-md-9
        .panel
          .panel-heading
            h3.panel-title = t '.new_topic'

          .panel-body
            = render 'form', topic: @topic

app/views/topics/search.html.slim
- @page_title = "#{t '.search'} #{params[:q]}"

.main
  .container
    .row
      .col-md-9
        .panel
          .panel-heading
            h3.panel-title
              = t '.search'
              '
              = params[:q]
          .panel-body
            .list-group.list-group-campo
              - if @topics.any?
                = render @topics
              - else
                .list-group-item.text-center.text-muted.empty-message
                  = t '.no_matching_results'
          - if @topics.total_pages > 1
            .panel-footer.clearfix
              .pull-right
                = paginate @topics, theme: 'campo'
      .col-md-3
        = render 'search_form'

app/views/topics/show.html.slim
- @page_title = @topic.title

.main
  .container
    .row
      .col-md-9
        .panel
          .panel-heading
            h1.panel-title = @topic.title
          .panel-body
            - cache [@topic, locale] do
              .list-group.list-group-campo
                .list-group-item.comment data-creator-id=@topic.user_id
                  a.list-group-item-avatar href=user_link(@topic.user)
                    img.img-rounded alt="avatar" src=@topic.user.avatar.normal.url
                  .list-group-item-content
                    .list-group-item-heading
                      a.comment-user href=user_link(@topic.user)
                        b = @topic.user.name
                        '
                        = "@#{@topic.user.username}"
                      = ' · '
                      a href=topic_path(@topic)
                        = time_ago_tag @topic.created_at
                      - if @topic.category
                        = ' · '
                        a href=categoried_topics_path(category_id: @topic.category.slug)
                          = @topic.category.name
                    article.comment-body
                      = markdown_format @topic.body
                    .list-group-item-actions.clearfix
                      .pull-right
                        a.btn id="like-for-topic-#{@topic.id}" href=topic_like_path(@topic) data-remote="true" data-method="post"
                          i.fa.fa-heart
                          '
                          span.count
                            - if @topic.likes_count > 0
                              = @topic.likes_count
                        a.btn data-visible-to="creator" href=edit_topic_path(@topic)
                          i.fa.fa-pencil
                        a.btn data-visible-to="creator" href=trash_topic_path(@topic) data-remote="true" data-method="delete" data-confirm=t('.delete_confirm')
                          i.fa.fa-trash-o

        .panel#comments
          .panel-heading
            h3.panel-title
              = t '.comments'
          .panel-body
            ul.list-group.list-group-campo id="comments-for-topic-#{@topic.id}"
              - if @comments.any?
                = render @comments
              - else
                li.list-group-item.text-center.text-muted.empty-message
                  = t '.no_comment_yet'
          - if @comments.total_pages > 1
            .panel-footer.clearfix
              .pull-right
                = paginate @comments, theme: 'campo', params: { anchor: 'comments' }

        .panel
          .panel-body
            - if login?
              - unless current_user.locked?
                .list-group.list-group-campo
                  .list-group-item.comment
                    a.list-group-item-avatar href=user_link(current_user)
                      img.img-rounded alt="avatar" src=current_user.avatar.normal.url
                    .list-group-item-content
                      .list-group-item-heading
                        a.comment-user href=user_link(current_user)
                          b = current_user.name
                          '
                          = "@#{current_user.username}"
                      = form_for @topic.comments.new, url: topic_comments_path(@topic), remote: true do |f|
                        .form-group
                          = markdown_area f, :body
                        = f.submit t('.add_this_comment'), class: 'btn btn-success', 'data-disable-with' => t('.add_this_comment')
              - else
                = t '.your_account_had_been_locked'
            - else
              a href=signup_path(return_to: request.fullpath)
                = t '.sign_up'
              '
              = t '.or'
              '
              a href=login_path(return_to: request.fullpath)
                = t '.login'
              '
              = t '.to_comment'

      .col-md-3
        - if login?
          .panel
            .panel-body
              = render 'subscriptions/subscription', subscribable: @topic

        .panel
          .panel-heading
            h4.panel-title
              = t '.related_topics'
          .panel-body
            - cache [@topic, 'related_topics', locale] do
              .list-group.list-group-campo
                - more_like_this_topics = @topic.more_like_this
                - if more_like_this_topics.any?
                  - more_like_this_topics.each do |topic|
                    a.list-group-item href=topic_path(topic)
                      = topic.title
                - else
                  .list-group-item.text-center.text-muted
                    = t '.no_more_topics'

- if login?
  - if @topic.liked_by?(current_user)
    javascript:
      campo.Likes.updateLike('topic', #{@topic.id});

  javascript:
    campo.Likes.updateLikes('comment', #{current_user.likes.where(likeable_type: 'Comment', likeable_id: @comments.pluck(:id)).pluck(:likeable_id)});

    $('#new_comment').validate({
      rules: {
        'comment[body]': {
          required: true
        }
      },
      messages: {
        'comment[body]': {
          required: '#{Comment.new.errors.generate_message :body, :blank}'
        }
      }
    });

app/views/topics/update.js.erb
<% if @topic.errors.empty? %>
  Turbolinks.visit('<%= topic_path(@topic) %>');
<% end %>