config/routes.rb
class AdminConstraint
  def self.matches?(request)
    if request.session[:user_id]
      user = User.find request.session[:user_id]
      user && user.admin?
    end
  end
end

Rails.application.routes.draw do
  get 'signup', to: 'users#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'

  post 'markdown/preview', to: 'markdown#preview'

  resources :users, only: [:create] do
    collection do
      get :check_email
      get :check_username
    end
  end

  namespace :users do
    resource :password, only: [:show, :new, :create, :edit, :update]
    resource :confirmation, only: [:new, :show, :create]
  end

  concern :commentable do
    resources :comments, only: [:create]
  end

  concern :likeable do
    resource :like, only: [:create, :destroy]
  end

  concern :subscribable do
    resource :subscription, only: [:update, :destroy]
  end

  resources :topics, only: [:index, :show, :new, :create, :edit, :update], concerns: [:commentable, :likeable, :subscribable] do
    collection do
      get 'categoried/:category_id', to: 'topics#index', as: :categoried
      get 'search'
    end

    member do
      delete :trash
    end
  end

  resources :comments, only: [:edit, :update], concerns: [:likeable] do
    member do
      get :cancel
      delete :trash
    end
  end

  resources :notifications, only: [:index, :destroy] do
    collection do
      post :mark
      delete :clear
    end
  end

  resources :attachments, only: [:create]

  root 'topics#index'

  scope path: '~:username', module: 'users', as: 'user' do
    resources :topics, only: [:index] do
      collection do
        get :likes
      end
    end
    resources :comments, only: [:index] do
      collection do
        get :likes
      end
    end

    root to: 'topics#index'
  end

  namespace :settings do
    resource :account, only: [:show, :update]
    resource :password, only: [:show, :update]
    resource :profile, only: [:show, :update]
    resource :notifications, only: [:show, :update]
  end

  namespace :admin do
    root to: 'dashboard#show'

    resources :users, only: [:index, :show, :update, :destroy] do
      collection do
        get :locked
      end

      member do
        patch :lock
        delete :lock, action: 'unlock'
      end
    end

    resources :categories, except: [:edit]

    resources :topics, only: [:index, :show, :update] do
      collection do
        get :trashed
      end

      member do
        delete :trash
        patch :restore
      end
    end

    resources :comments, only: [:index, :show, :update] do
      collection do
        get :trashed
      end

      member do
        delete :trash
        patch :restore
      end
    end

    resources :attachments, only: [:index, :destroy]
  end

  constraints(AdminConstraint) do
    mount Resque::Server.new, at: 'resque'
  end

  if Rails.env.development?
    get 'qunit', to: 'qunit#index'
  end
end

app/models/notification.rb
class Notification < ActiveRecord::Base
  belongs_to :user
  belongs_to :subject, polymorphic: true

  scope :named, -> (name) { where(name: name) }
  scope :unread, -> { where(read: false) }
end

app/controllers/notifications_controller.rb
class NotificationsController < ApplicationController
  before_action :login_required
  after_action :mark_all_as_read, only: [:index]

  def index
    @notifications = current_user.notifications.includes(:subject).order(id: :desc).page(params[:page])
  end

  def destroy
    @notification = current_user.notifications.find params[:id]
    @notification.destroy
  end

  def clear
    current_user.notifications.delete_all
  end

  private

  def mark_all_as_read
    current_user.notifications.unread.update_all(read: true, updated_at: Time.now.utc)
  end
end

app/controllers/settings/notifications_controller.rb
class Settings::NotificationsController < Settings::ApplicationController
  def show
  end

  def update
    if @user.update_attributes params.require(:user).permit(:send_mention_email, :send_mention_web, :send_comment_email, :send_comment_web)
      flash[:success] = I18n.t('settings.notifications.flashes.successfully_updated')
      redirect_to settings_notifications_url
    else
      render :show
    end
  end
end

app/helpers/notifications_helper.rb
module NotificationsHelper
  def unread_notifications_count
    if login?
      current_user.notifications.unread.count
    end
  end
end

app/views/notifications/clear.js.erb
Turbolinks.visit('<%= notifications_path %>');

app/views/notifications/destroy.js.erb
$('#notification_<%= @notification.id %>').slideUp(function () { $(this).remove() });

app/views/notifications/index.html.slim
.main
  .container
    .row
      .col-md-8.col-md-push-2
        .panel
          .panel-heading
            .pull-right
              a.btn.btn-default href=settings_notifications_path
                i.fa.fa-cog
              '
              a.btn.btn-default href=clear_notifications_path data-remote="true" data-method="delete" data-confirm=t('.delete_all_confirm')
                = t '.delete_all'
            h3.panel-title
              = t '.notifications'
          .panel-body
            ul.list-group.list-group-campo
              - if @notifications.any?
                - @notifications.each do |notification|
                  = render "notifications/notification/#{notification.name}", notification: notification
              - else
                li.list-group-item.text-center.text-muted.empty-message
                  = t '.no_notifications'
          .panel-footer.clearfix
            .pull-right
              = paginate @notifications, theme: 'campo'

app/views/notifications/mark.js.erb
Turbolinks.visit('<%= notifications_path %>');